# Generated by Django 4.1.1 on 2023-03-16 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Phone_number', models.IntegerField()),
                ('Mail_id', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('Address', models.TextField(max_length=600)),
                ('Material_Provide', models.BooleanField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.department')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.course')),
            ],
        ),
    ]
