# Generated by Django 4.1.7 on 2023-03-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Department',
            new_name='departname',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Mail_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Material_Provide',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Phone_number',
        ),
        migrations.AlterField(
            model_name='application',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
