# Generated by Django 4.1.1 on 2023-03-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_material'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Materials',
        ),
        migrations.AddField(
            model_name='application',
            name='materials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='studentapp.materials'),
            preserve_default=False,
        ),
    ]
