# Generated by Django 4.1.7 on 2023-03-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_rename_material_materials_application_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='materials',
        ),
        migrations.AddField(
            model_name='application',
            name='materials',
            field=models.ManyToManyField(to='studentapp.materials'),
        ),
    ]
